# 1. OpenJDK 이미지를 사용하여 기반 이미지 설정
FROM openjdk:17-jdk-alpine as build

# 2. 작업 디렉토리 설정
WORKDIR /workspace/app

# 3. 의존성 파일만 먼저 복사하여 캐시 이점 활용
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .

# 4. 프로젝트 내 모든 소스 코드 복사
COPY src src

# 5. 실행 권한 부여 및 프로젝트 빌드
# gradlew에 실행 권한이 없는 경우 아래 RUN 명령을 통해 부여
RUN chmod +x ./gradlew
RUN ./gradlew build -x test

# 6. 애플리케이션 실행을 위한 새로운 단계
FROM openjdk:17-jdk-alpine

WORKDIR /app

EXPOSE 8080

# 빌드 단계에서 생성된 JAR 파일 복사
COPY --from=build /workspace/app/build/libs/*.jar app.jar

# 애플리케이션 실행
ENTRYPOINT ["java","-jar","app.jar"]