# Node.js 버전을 20.11.0로 설정
FROM node:20.11.0

# 작업 디렉토리 설정
WORKDIR /user/src/app

# package.json 및 package-lock.json (있는 경우) 복사
COPY package*.json ./

# npm 대신 npm@10.2.4 버전을 명시적으로 설치
RUN npm install -g npm@10.2.4

# 프로젝트 의존성 설치
RUN npm install

# 나머지 프로젝트 파일 복사
COPY ./ ./

# # 애플리케이션이 8080 포트에서 실행될 것으로 예상(확인 필요)
EXPOSE 5173

# 애플리케이션 실행
CMD ["npm", "run", "dev", "--", "--host"]
